config/routes.rb
Fogblog::Application.routes.draw do
  
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/contacts', to: 'static_pages#contacts', via: 'get'
  match '/profile', to: 'persons#profile', as: 'user_root', via: 'get'

  devise_for :users, :path => '', :path_names => {:sign_up => 'signup', :sign_in => 'login', :sign_out => 'logout'}
  devise_scope :user do get "/signup" => "devise/registrations#new"
  end
  devise_scope :user do get "/login" => "devise/sessions#new"
  end
  devise_scope :user do get "/logout" => "devise/sessions#destroy"
  end
  
  get "create_post/index"
  get "create_post/show"
  get "create_post/preview"
  get "create_post/publish"
  get "create_post/save"

  

   root to: 'static_pages#home'
   

end

app/models/user.rb
class User < ActiveRecord::Base
    

	 attr_accessor :login
	 mount_uploader :avatar, AvatarUploader
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  validates :username, :uniqueness => { :case_sensitive => false },
  :format => { :with => /\A[A-z][A-z0-9_-].{4,20}\z/,
  :message => "Nickname should contain at least 4 characters, but not more than 20." }
 
  #validates_presence_of   :avatar
  #validates_integrity_of  :avatar
  #validates_processing_of :avatar
  def login=(login)
    @login = login
  end

  def login
    @login || self.username || self.email
  end

  def self.find_first_by_auth_conditions(warden_conditions)
      conditions = warden_conditions.dup
    if login = conditions.delete(:login)
        where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
        where(conditions).first
    end
  end


 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	 before_filter :configure_permitted_parameters, if: :devise_controller?
	  protected
	def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:first_name, :last_name, :username, :email, :password, :password_confirmation, :remember_me, :avatar, :avatar_cache, :remove_avatar) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :username, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:first_name, :last_name, :username, :email, :password, :password_confirmation, :current_password, :avatar, :avatar_cache, :remove_avatar) }
  	
  
    end
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/create_post_controller.rb
class CreatePostController < ApplicationController
	before_filter :authenticate_user!
	def index
	end

	def show
	end

	def preview
	end

	def publish
	end

	def save
	end
end

app/controllers/persons_controller.rb
class PersonsController < ApplicationController
  def profile
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	def new
	end
	
	def index
		@posts = Post.all		
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contacts
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def full_title(page_title)
		base_title  = "FogBlog"
	if page_title.empty? 
		base_title
	else
	"#{base_title} | #{page_title}"
end
end

end

app/helpers/create_post_helper.rb
module CreatePostHelper
end

app/helpers/persons_helper.rb
module PersonsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/create_post/index.html.erb
<h1>Редактор публикации.</h1>
<div id="newpost">
INPUTAREA





SAVE | PREVIEW | PUBLISH
</div>

app/views/create_post/show.html.erb
<h1>Редактор публикации.</h1>
<div id="newpost">
<%= check_box_tag(:pet_dog) %>
<%= label_tag(:pet_dog, "I own a dog") %>
<%= check_box_tag(:pet_cat) %>
<%= label_tag(:pet_cat, "I own a cat") %>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://railstutorial.org/">Rails Tutorial</a>
    by Michael Hartl
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contacts_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "sample app", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home",    root_path %></li>
          <li><%= link_to "Help",    help_path %></li>
          <li><% if user_signed_in? %>
  
  <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>        
  
<% else %>
 
  <%= link_to('Login', new_user_session_path)  %>  
  
<% end %>
</li>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim'%>
  </head>
  <body>
    <div class="block">
    <%= render 'layouts/header' %>
    
    <div class="container">
      <%= yield %>
    <%= render 'layouts/footer' %>
    </div>
  </div>
  </body>
</html>

app/views/persons/profile.html.erb
<h1>Персональная информация</h1>
<div class="avatar"><%= image_tag(current_user.avatar.url) %></div>
<p><%= current_user.username %>
</p>
<p><%= current_user.first_name %> <%= current_user.last_name %>
</p>
<p><%= current_user.email %>
</p>
<p><%= current_user %>
<p><%= link_to "Edit", edit_user_registration_path %>	|	<%= link_to "Log out", destroy_user_session_path, :method => :delete %></p>
</p>

app/views/posts/new.html.erb
<h1>New Post</h1>
<div class='postbox'>
<%= form_for :post do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>
</div>

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>

    <h1>About me</h1>
    <p>
      I am learning rails bro! 
    </p>
    <p>Клип снимался в Лос-Анджелесе. Существуют две версии клипа, из одной вырезаны сцены насилия. На телевидении вышла отцензурированная версия, где были вырезаны сцена избиения, непристойный жест и кровь на простыне.

Волкова и Катина приезжают в ресторан с корейскими иероглифами, где беседуют и употребляют спиртные напитки. Между ними происходит конфликт, и Волкова покидает ресторан. Волкова идёт по ночной улице в наряде, напоминающем наряд проститутки. Она соглашается сесть в машину к молодому человеку, который привозит её на квартиру.

Они оказываются в постели, приступая к любовным ласкам. Однако молодой человек начинает действовать грубо, Волкова вырывается и показывает ему непристойный жест. В ответ он начинает наносить телесные повреждения, бросив её, в частности, на стеклянный столик. Волкова отползает в сторону и стреляет ему в лицо. Кровь и мозги последнего размазываются по висящей простыне. Волкова пинает труп и вылезает через окно на улицу, где к ней подъезжает Катина.
Список композиций
Европа

Maxi CD-Single — September 30, 2005

    All about us (Single Version)
    Divine (Non-LP Long Version)
    All about us (Stephane K Radio Mix)
    All about us (Uncensored Closed Captioned / Video)

2 Track CD-Single

    All about us (Single Version)
    Divine (Non-LP Long Version)

Япония

CD-Single — September 1, 2005

    All About Us
    All About Us (Instrumental/Karaoke)

Тайвань

Limited Edition Remixes Promo Single

    Dave Aude Big Room Vocal
    Dave Aude Vocal Edit
    Dave Aude Big Club Dub
    Dave Aude Big Mixshow
    Dave’s Acid Funk Dub
    Stephane K Radio Mix
    Stephane K Extended Mix
    Stephane K Guitar Dub Mix
    The Lovermakers Mix
    Glam As You Mix by Guena LG
    Glam As You Radio Mix by Guena LG
    Sunset In Ibiza Mix by Guena LG
    Sunset In Ibiza Radio Mix by Guena LG

Великобритания

Maxi CD-Single — September 26, 2005

    All About Us (Single Version)
    Divine (Non-LP Long Version)
    All About Us (The Aude' Vocal Edit)
    All About Us (Stephane K Radio Mix)
    All About Us (Edited Version/Closed Captioned)

Second Edition

    All About Us
    All The Things She Said

DVD Single

    All About Us Video (Uncensored Version)
    All About Us (Glam As You Mix By Guena LG)
    All About Us (The Lovemakers Mix)

All About Us (Remixes) — August 2005 (Promotional-CD only)

    All About Us (Dave Aude' Big Mixshow) (5:33)
    All About Us (Stephane K Extended Mix) (6:24)
    All About Us (Glam As You Mix by Gue’na LG) (6:26)
    All About Us (Dave’s Acid Funk Dub) (8:17)
    All About Us (Single Version) (3:02)

DVD Promo single

    Unsensored Video
    Edited Version

    </p>

app/views/static_pages/contacts.html.erb
<% provide(:title, 'Contacts') %>
<h1>Contacts</h1>
<p>
<a href="http://infinite-savannah-3264.herokuapp.com/">FogBlog</a></p>
 <p>skype: FogFreek</p>
 <br />
 <p>Alexandr Mutskiy</p>
 <p>tel: +(420)775419656</p> 

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>

    <h1>Help</h1>
    <p>
      This page can help you.
    </p>
 

app/views/static_pages/home.html.erb
<div class="center hero-unit">
  <h1>Welcome to the Sample App</h1>

  <h2>
    This is the home page for the
    <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
    sample application.
  </h2>


  <%= link_to "Sign up now!", signup_path, class: "btn btn-large" %>
</div>

<%= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/' %>
<%= link_to image_tag("ruby.png", alt: "Ruby"), 'http://ruby-lang.org/' %>

app/views/welcome/index.html.erb
<h1>Hi Rails</h1>
<p>First page</p>